# Generated by Django 2.2.3 on 2019-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollageDetails',
            fields=[
                ('col_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=30)),
                ('m_student', models.IntegerField()),
                ('f_student', models.IntegerField()),
                ('image', models.ImageField(upload_to='collage_pic/')),
            ],
        ),
    ]
