# Generated by Django 2.2.3 on 2019-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0002_collagedetails_col_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collagedetails',
            name='col_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collagedetails',
            name='col_name',
            field=models.CharField(max_length=80),
        ),
    ]
