# Generated by Django 2.2.3 on 2019-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0003_auto_20190827_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='collagedetails',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collagedetails',
            name='col_id',
            field=models.IntegerField(unique=True),
        ),
    ]
