# Generated by Django 2.2.3 on 2019-08-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0004_auto_20190827_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collagedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='collagedetails',
            name='col_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collagedetails',
            name='col_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
