# Generated by Django 2.2.3 on 2019-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0005_auto_20190827_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('m_student', models.IntegerField()),
                ('f_student', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='collagedetails',
            name='f_student',
        ),
        migrations.RemoveField(
            model_name='collagedetails',
            name='m_student',
        ),
        migrations.RemoveField(
            model_name='collagedetails',
            name='course',
        ),
        migrations.AddField(
            model_name='collagedetails',
            name='course',
            field=models.ManyToManyField(to='coll.Course'),
        ),
    ]
