# Generated by Django 2.2.3 on 2019-08-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coll', '0006_auto_20190828_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='collagedetails',
            name='f_student',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagedetails',
            name='m_student',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='collagedetails',
            name='course',
        ),
        migrations.AddField(
            model_name='collagedetails',
            name='course',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
